name: NDS M30 M1 Live Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests matplotlib

      - name: Run NDS M30 M1 Scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python nds_m30_m1_live_scanner.py
